version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13.3
    environment:
      POSTGRES_USER: kode
      POSTGRES_PASSWORD: 5427
      POSTGRES_DB: kode
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/potgresql/data

volumes:
  pgdata: {}